### PR TITLE
Extract user entity from JWT

### PR DESCRIPTION
**Pull request by amirphl**
There is a bunch of the codes which extract `userID` from the `Authorization` header and I think it's duplicate code. What about replacing all duplicate codes with the provided function?

### CODE REVIEW

**Comment by adiatma85** [comment]
+1 in this.
But how we or when we call it? I mean, in this case, we only get the token at middleware, right?

I think something like this

```golang
func (s *jwtService) ExtractToken() string // this return token in string
 
// And

func (s *jwtService) ExtractUser() entity.User // this is your function to extract user
```

So, if I need user entity in handler, I can call it like
```golang
func MyHandler(context *gin.Context){
  jwtService := service.NewJwtService()
 userRepo := repository.NewUserRepository()
 user := jwtService.ExtractUser(jwtService.ExtractToken(), userRepo)
}
```

**Comment by adiatma85** [comment]
Actually, wait @amirphl 
```golang
t := j.ValidateToken(token, &gin.Context{})
```

Does this mean that we sending new Context?
I mean, as we can see at ``AuthorizeJWT`` at ``jwt.service.go``, it send the previous context, not the new one.

I don't know whether if this actually works (where we initiate new context and send it), but in my opinion, you should use previous context to make the "variables" persist, i.e Authorization Header, Request Boyd, etc

Thanks in advance (and I hope you understand what I meaning here)

**Comment by amirphl** [comment]
It's possible to simply remove the token validation since the caller is sending the token and we can assume that the caller is responsible for the token validation.
a question: Does it matter what the Gin context is?

**Comment by adiatma85** [comment]
Yes, exactly like that

**Pull request closed without merging**
